version: '3'

services:
  db_postgres:
    container_name: 'db_boilerplate'
    image: 'postgres:14.5-alpine'
    restart: always
    env_file:
      - .env
    ports:
      - '5400:5432'
    volumes:
      - ./database/boilerplate:/var/lib/postgresql/data/

  be_boilerplate:
    entrypoint: /bin/sh './scripts/be-node-dev.sh'
    env_file:
      - .env
    ports:
      - '4000:4000'
    depends_on:
      - db_postgres
    links:
      - db_postgres

  be_boilerplate_test:
    container_name: 'be_boilerplate_test'
    command: sh -c "echo 'Test container ready' && tail -f /dev/null"
    build: .
    stdin_open: true
    tty: true
    depends_on:
      - db_postgres
    links:
      - db_postgres
    env_file:
      - .env
    volumes:
      - .:/app/
      - /app/node_modules
      
  pgadmin4:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: parola
    volumes:
    - ./servers.json:/pgadmin4/servers.json

  redis:
    image: redis
    ports:
      - "6379:6379"  